/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSponsorsRouteImport } from './routes/_app.sponsors'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppMembershipRouteImport } from './routes/_app.membership'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppFilmsRouteImport } from './routes/_app.films'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommunicationsRouteImport } from './routes/_app.communications'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSponsorsRoute = AppSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppMembershipRoute = AppMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppFilmsRoute = AppFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationsRoute = AppCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/communications': typeof AppCommunicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/films': typeof AppFilmsRoute
  '/members': typeof AppMembersRoute
  '/membership': typeof AppMembershipRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/sponsors': typeof AppSponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/communications': typeof AppCommunicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/films': typeof AppFilmsRoute
  '/members': typeof AppMembersRoute
  '/membership': typeof AppMembershipRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/sponsors': typeof AppSponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/communications': typeof AppCommunicationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/films': typeof AppFilmsRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/membership': typeof AppMembershipRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sponsors': typeof AppSponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/communications'
    | '/dashboard'
    | '/events'
    | '/films'
    | '/members'
    | '/membership'
    | '/resources'
    | '/settings'
    | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/communications'
    | '/dashboard'
    | '/events'
    | '/films'
    | '/members'
    | '/membership'
    | '/resources'
    | '/settings'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/communications'
    | '/_app/dashboard'
    | '/_app/events'
    | '/_app/films'
    | '/_app/members'
    | '/_app/membership'
    | '/_app/resources'
    | '/_app/settings'
    | '/_app/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sponsors': {
      id: '/_app/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AppSponsorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/membership': {
      id: '/_app/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AppMembershipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/films': {
      id: '/_app/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof AppFilmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communications': {
      id: '/_app/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AppCommunicationsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCommunicationsRoute: typeof AppCommunicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRoute
  AppFilmsRoute: typeof AppFilmsRoute
  AppMembersRoute: typeof AppMembersRoute
  AppMembershipRoute: typeof AppMembershipRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSponsorsRoute: typeof AppSponsorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunicationsRoute: AppCommunicationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRoute,
  AppFilmsRoute: AppFilmsRoute,
  AppMembersRoute: AppMembersRoute,
  AppMembershipRoute: AppMembershipRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSponsorsRoute: AppSponsorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
